import type { AgentSession } from "./types";

export const mockSessions: AgentSession[] = [
  {
    tool: "codex",
    sessionId: "codex-mecho-01",
    cwd: "G:\\PROJECT\\Mecho",
    title: "Codex - Mecho",
    state: "running",
    lastEvent: "PostToolUse",
    lastMessage: "Inspecting agent workflow docs and checking task boundaries.",
    needsAttention: false,
    windowHint: {
      process: "WindowsTerminal.exe",
      title: "Codex - Mecho",
      titleToken: "[AMO:codex:mecho:planning]",
      titleContains: ["Codex", "Mecho"],
      project: "Mecho",
      cwd: "G:\\PROJECT\\Mecho",
      tool: "codex",
    },
    updatedAt: "2026-05-07T17:32:00+08:00",
  },
  {
    tool: "claude",
    sessionId: "claude-mining-ui",
    cwd: "G:\\PROJECT\\project_mining",
    title: "Claude - project_mining Battle UI",
    state: "waiting_permission",
    lastEvent: "PreToolUse",
    lastMessage: "Needs approval before running Unity verification.",
    needsAttention: true,
    windowHint: {
      process: "WindowsTerminal.exe",
      title: "Claude - project_mining",
      titleToken: "[AMO:claude:project-mining:battle-ui]",
      titleContains: ["Claude", "project_mining"],
      project: "project_mining",
      cwd: "G:\\PROJECT\\project_mining",
      tool: "claude",
    },
    updatedAt: "2026-05-07T17:30:00+08:00",
  },
  {
    tool: "codex",
    sessionId: "codex-commonproject",
    cwd: "G:\\PROJECT\\CommonProject",
    title: "Codex - CommonProject",
    state: "completed",
    lastEvent: "TurnComplete",
    lastMessage: "Generated local image service validation report.",
    needsAttention: false,
    windowHint: {
      process: "WindowsTerminal.exe",
      title: "Codex - CommonProject",
      titleToken: "[AMO:codex:commonproject:image-service]",
      titleContains: ["Codex", "CommonProject"],
      project: "CommonProject",
      cwd: "G:\\PROJECT\\CommonProject",
      tool: "codex",
    },
    updatedAt: "2026-05-07T17:22:00+08:00",
  },
  {
    tool: "claude",
    sessionId: "claude-kommon-run",
    cwd: "G:\\PROJECT\\Kommon-Run",
    title: "Claude - Kommon-Run",
    state: "failed",
    lastEvent: "ToolError",
    lastMessage: "Vitest command failed after enemy tuning change.",
    needsAttention: true,
    windowHint: {
      process: "WindowsTerminal.exe",
      title: "Claude - Kommon-Run",
      titleToken: "[AMO:claude:kommon-run:enemy-lab]",
      titleContains: ["Claude", "Kommon-Run"],
      project: "Kommon-Run",
      cwd: "G:\\PROJECT\\Kommon-Run",
      tool: "claude",
    },
    updatedAt: "2026-05-07T17:18:00+08:00",
  },
  {
    tool: "other",
    sessionId: "manual-review",
    cwd: "G:\\PROJECT\\AgentMonitorOverlay",
    title: "Manual Review",
    state: "unknown",
    lastEvent: "NoHeartbeat",
    lastMessage: "No broker heartbeat yet; mock fallback is active.",
    needsAttention: false,
    windowHint: {
      process: "explorer.exe",
      title: "AgentMonitorOverlay",
      titleContains: ["AgentMonitorOverlay"],
      project: "AgentMonitorOverlay",
      cwd: "G:\\PROJECT\\AgentMonitorOverlay",
      tool: "other",
    },
    updatedAt: "2026-05-07T17:10:00+08:00",
  },
];
